---
all:
  hosts:
    ftd:
      ansible_host: ec2-34-198-74-215.compute-1.amazonaws.com
      ansible_network_os: ftd
      ansible_user: admin
      ansible_password: Cisco123
      ansible_httpapi_port: 443
      ansible_httpapi_use_ssl: True
      ansible_httpapi_validate_certs: False