---
all:
  hosts:
    ftd:
      ansible_host: 
      ansible_network_os: ftd
      ansible_user: 
      ansible_password: 
      ansible_httpapi_port: 443
      ansible_httpapi_use_ssl: True
      ansible_httpapi_validate_certs: False
