- hosts: all
  connection: httpapi

  # NETWORK OBJECTS

  tasks:
    - name: Add Remote Site Host
      ftd_configuration:
        operation: 'addNetworkObject'
        data:
          name: "remote_site"
          description: "remote host"
          subType: "HOST"
          value: "100.11.24.44"
          type: "networkobject"
        register_as: "remote_site"
      register: result
    - name: Add K8s Cluster Host
      ftd_configuration:
        operation: 'addNetworkObject'
        data:
          name: "K8s_Cluster"
          description: "Kubernetes Cluster"
          subType: "HOST"
          value: "10.0.1.100"
          type: "networkobject"
        register_as: "K8s_Cluster"
      register: result
    - name: Add K8s Nat Host
      ftd_configuration:
        operation: 'addNetworkObject'
        data:
          name: "K8s_ext"
          description: "Kubernetes Cluster Nat address"
          subType: "HOST"
          value: "10.0.0.11"
          type: "networkobject"
        register_as: "K8s_ext"
      register: result
