- hosts: all
  connection: httpapi

  tasks:
    - name: addNetworkObject should create a new network
      ftd_configuration:
        operation: 'addNetworkObject'
        data:
          name: "ansible-test-network"
          description: "Ansible Integration tests in action"
          subType: "HOST"
          value: "192.22.22.24"
          type: "networkobject"
        register_as: "testObj"
      register: result
