---
all:
  hosts:
    ftd:
      ansible_host: ec2-3-141-213-141.us-east-2.compute.amazonaws.com
      ansible_network_os: ftd
      ansible_user: admin
      ansible_password: Cisco@123
      ansible_httpapi_port: 443
      ansible_httpapi_use_ssl: True
      ansible_httpapi_validate_certs: False